import React, { useState, useMemo } from 'react';
import { useAuth } from '../context/AuthContext';
import { useProducts } from '../context/ProductContext';
import { PageContainer } from '../components/layout/PageContainer';
import { PageHeader } from '../components/ui/PageHeader';
import { Card, CardHeader, CardTitle, CardContent } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { Input } from '../components/ui/Input';
import { WalletAddress } from '../components/ui/WalletAddress';
import { Activity, ExternalLink, Search, Clock, Info } from 'lucide-react';

const METHOD_LABELS: Record<string, string> = {
  PRODUCT_REGISTERED: 'register_product(string,string,string)void',
  TRANSFER_INITIATED: 'transfer_product(string,string,uint8)void',
  PRODUCT_TRANSFERRED: 'transfer_product(string,string,uint8)void',
  RECEIPT_CONFIRMED: 'receive_product(string)void',
  PRODUCT_RECEIVED: 'receive_product(string)void',
  PRODUCT_RECALLED: 'recall_product(string)void',
  COUNTERFEIT_REPORTED: 'report_counterfeit(string,string)void',
};

const EVENT_BADGES: Record<string, { label: string; color: string }> = {
  PRODUCT_REGISTERED: { label: 'PRODUCT_REGISTERED', color: 'bg-sky-100 text-sky-800 border-sky-300' },
  TRANSFER_INITIATED: { label: 'PRODUCT_TRANSFERRED', color: 'bg-teal-100 text-teal-800 border-teal-300' },
  PRODUCT_TRANSFERRED: { label: 'PRODUCT_TRANSFERRED', color: 'bg-teal-100 text-teal-800 border-teal-300' },
  RECEIPT_CONFIRMED: { label: 'PRODUCT_RECEIVED', color: 'bg-emerald-100 text-emerald-800 border-emerald-300' },
  PRODUCT_RECEIVED: { label: 'PRODUCT_RECEIVED', color: 'bg-emerald-100 text-emerald-800 border-emerald-300' },
  PRODUCT_RECALLED: { label: 'PRODUCT_RECALLED', color: 'bg-rose-100 text-rose-800 border-rose-300' },
  COUNTERFEIT_REPORTED: { label: 'COUNTERFEIT_REPORTED', color: 'bg-amber-100 text-amber-800 border-amber-300' },
};

export const BlockchainActivityPage: React.FC = () => {
  const { network } = useAuth();
  const { historyEvents } = useProducts();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('ALL');

  const loraBaseUrl =
    network === 'LocalNet'
      ? 'https://lora.algokit.io/localnet/transaction/'
      : network === 'TestNet'
      ? 'https://lora.algokit.io/testnet/transaction/'
      : 'https://lora.algokit.io/mainnet/transaction/';

  const filtered = useMemo(() => {
    let result = historyEvents;

    if (selectedCategory !== 'ALL') {
      result = result.filter((e) => {
        if (selectedCategory === 'REGISTERED') return e.eventType === 'PRODUCT_REGISTERED';
        if (selectedCategory === 'TRANSFERRED') return e.eventType === 'TRANSFER_INITIATED' || e.eventType === 'PRODUCT_TRANSFERRED';
        if (selectedCategory === 'RECEIVED') return e.eventType === 'RECEIPT_CONFIRMED' || e.eventType === 'PRODUCT_RECEIVED';
        if (selectedCategory === 'RECALLED') return e.eventType === 'PRODUCT_RECALLED';
        if (selectedCategory === 'COUNTERFEIT') return e.eventType === 'COUNTERFEIT_REPORTED';
        return true;
      });
    }

    const q = searchQuery.trim().toLowerCase();
    if (q) {
      result = result.filter(
        (e) =>
          e.txId?.toLowerCase().includes(q) ||
          e.productId.toLowerCase().includes(q) ||
          e.eventType.toLowerCase().includes(q) ||
          e.previousHolder.toLowerCase().includes(q) ||
          e.newHolder.toLowerCase().includes(q)
      );
    }

    return result;
  }, [historyEvents, searchQuery, selectedCategory]);

  return (
    <PageContainer>
      <PageHeader
        title="Algorand Blockchain Activity Stream"
        description="Immutable AVM transaction log generated by BlockTrace ARC-4 smart contract method calls."
        breadcrumbs={[{ label: 'Blockchain Activity' }]}
      />

      {/* Network notice */}
      <div className="mb-4 p-3 bg-blue-50 border border-blue-200 rounded-xl flex items-start gap-3 text-xs text-blue-900">
        <Info className="w-4 h-4 text-blue-500 shrink-0 mt-0.5" />
        <span>
          Live transaction audit trail connected to <strong>Algorand {network}</strong>. Real transaction hashes generated upon smart contract invocation.
        </span>
      </div>

      <Card variant="default">
        <CardHeader>
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <CardTitle className="flex items-center gap-2">
              <Activity className="w-5 h-5 text-teal-600" /> AVM Transaction Stream ({filtered.length})
            </CardTitle>

            {/* Filter buttons & Search */}
            <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2">
              <div className="flex items-center gap-1 overflow-x-auto pb-1 sm:pb-0">
                {['ALL', 'REGISTERED', 'TRANSFERRED', 'RECEIVED', 'RECALLED', 'COUNTERFEIT'].map((cat) => (
                  <button
                    key={cat}
                    onClick={() => setSelectedCategory(cat)}
                    className={`px-2.5 py-1 rounded-lg text-[11px] font-bold transition-colors whitespace-nowrap ${
                      selectedCategory === cat
                        ? 'bg-slate-900 text-white'
                        : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                    }`}
                  >
                    {cat}
                  </button>
                ))}
              </div>

              <div className="w-full sm:w-60">
                <Input
                  placeholder="Search TxID, Product ID, Wallet..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  leftIcon={<Search className="w-4 h-4 text-slate-400" />}
                />
              </div>
            </div>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          {/* Desktop Table */}
          <div className="hidden md:block table-responsive">
            <table className="w-full text-left border-collapse text-xs">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                  <th className="py-3.5 px-5">Transaction ID</th>
                  <th className="py-3.5 px-5">Product ID</th>
                  <th className="py-3.5 px-5">Event / Method</th>
                  <th className="py-3.5 px-5">From</th>
                  <th className="py-3.5 px-5">To</th>
                  <th className="py-3.5 px-5">Timestamp</th>
                  <th className="py-3.5 px-5">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {filtered.length === 0 && (
                  <tr>
                    <td colSpan={7} className="py-10 text-center text-xs text-slate-400">
                      No matching blockchain events found.
                    </td>
                  </tr>
                )}
                {filtered.map((evt, idx) => {
                  const badge = EVENT_BADGES[evt.eventType];
                  const method = METHOD_LABELS[evt.eventType] || evt.eventType;
                  return (
                    <tr key={idx} className="hover:bg-slate-50/60 transition-colors table-row-animate">
                      <td className="py-3.5 px-5 font-mono text-slate-700">
                        <div className="flex items-center gap-1.5">
                          <span className="font-bold text-slate-900">
                            {evt.txId ? `${evt.txId.substring(0, 10)}…` : '—'}
                          </span>
                          {evt.txId && (
                            <a
                              href={`${loraBaseUrl}${evt.txId}`}
                              target="_blank"
                              rel="noreferrer"
                              className="text-slate-400 hover:text-teal-600 transition-colors"
                              title="View on Lora Explorer"
                            >
                              <ExternalLink className="w-3.5 h-3.5" />
                            </a>
                          )}
                        </div>
                      </td>
                      <td className="py-3.5 px-5 font-mono font-bold text-slate-900">{evt.productId}</td>
                      <td className="py-3.5 px-5">
                        <div className="space-y-1">
                          {badge && (
                            <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${badge.color}`}>
                              {badge.label}
                            </span>
                          )}
                          <p className="font-mono text-[11px] text-slate-500 truncate max-w-[200px]">{method}</p>
                        </div>
                      </td>
                      <td className="py-3.5 px-5"><WalletAddress address={evt.previousHolder} /></td>
                      <td className="py-3.5 px-5"><WalletAddress address={evt.newHolder} /></td>
                      <td className="py-3.5 px-5 font-mono text-slate-500">
                        <div className="flex items-center gap-1.5">
                          <Clock className="w-3 h-3 text-slate-400" />
                          {new Date(evt.timestamp).toLocaleString()}
                        </div>
                      </td>
                      <td className="py-3.5 px-5">
                        <Badge variant="success">CONFIRMED</Badge>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          {/* Mobile Cards */}
          <div className="md:hidden p-4 space-y-3">
            {filtered.length === 0 && (
              <div className="p-8 text-center text-xs text-slate-400 bg-slate-50 rounded-xl border border-slate-200">
                No matching events found.
              </div>
            )}
            {filtered.map((evt, idx) => {
              const badge = EVENT_BADGES[evt.eventType];
              return (
                <div key={idx} className="p-4 border border-slate-200 bg-slate-50 rounded-xl space-y-2">
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <p className="font-mono font-extrabold text-slate-900 text-sm">{evt.productId}</p>
                      <p className="font-mono text-[11px] text-slate-500 mt-0.5">
                        {evt.txId ? `${evt.txId.substring(0, 14)}…` : '—'}
                      </p>
                    </div>
                    {badge && (
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border shrink-0 ${badge.color}`}>
                        {badge.label}
                      </span>
                    )}
                  </div>
                  <div className="grid grid-cols-2 gap-2 text-xs">
                    <div>
                      <span className="text-slate-500 block">From:</span>
                      <WalletAddress address={evt.previousHolder} />
                    </div>
                    <div>
                      <span className="text-slate-500 block">To:</span>
                      <WalletAddress address={evt.newHolder} />
                    </div>
                  </div>
                  <div className="flex items-center justify-between text-[11px] font-mono text-slate-400 pt-1 border-t border-slate-200">
                    <span>{new Date(evt.timestamp).toLocaleString()}</span>
                    <Badge variant="success">CONFIRMED</Badge>
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>
    </PageContainer>
  );
};
